name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  branch-check:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/branch-check.yml

  test:
    needs: [branch-check]
    uses: ./.github/workflows/test.yml

  lint:
    needs: [branch-check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python environment
      uses: ./.github/actions/setup-python
      with:
        python-version: "3.10"
    
    - name: Run ruff
      run: poetry run ruff check src/rivusio
    
    - name: Run mypy
      run: poetry run mypy src/rivusio

  docs:
    needs: [branch-check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: poetry install --no-interaction
    
    - name: Build documentation
      run: poetry run mkdocs build --strict
    
    - name: Deploy documentation
      if: github.ref == 'refs/heads/main'
      run: poetry run mkdocs gh-deploy --force
