name: Test

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python environment
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Run tests with coverage
      run: |
        poetry run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
        override_commit: ${{ github.sha }}
        override_branch: ${{ github.ref_name }}
        override_pr: ${{ github.event.pull_request.number }}
        clean: true
        
    - name: Run mypy
      run: poetry run mypy src tests
